name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: us-east-1 # Specify your in to Amazon ECR" step, where the job fails with the AWS region here

      - name: Build Docker image
        run: |
          docker build -t my-strapi message `Region is missing`. This indicates that the-app .

      - name: Tag Docker image
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          docker tag teja:latest 307946639945.dkr.ecr.us-east-1.amazonaws.com/teja:latest:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: AWS region is not being set or passed to the `aws Push Docker image to ECR
        run: |
          docker push 307946639945.dkr.ecr.us-east-1.amazonaws.com/teja:latest:$IMAGE_TAG
